# Google Maps API Key (Usar variable de entorno)
google.maps.api.key=${GOOGLE_MAPS_API_KEY:demo-key-fallback}

# Configuraciones
server.port=8080
spring.application.name=FoodHunter
spring.profiles.active=prod
